const PRODUCTS = [
    {
      id: '1',
      name: 'Rule 1 Proteins 5Lbs (2.23kg)',
      color: '#f5428d',
      image: 'https://wheyshop.cdn.vccloud.vn/wp-content/uploads/2022/09/rule-1-proteins-5lbs-2-23kg-280x280.webp',
      categoryId: '1',
      description: 'Whey siêu vip,',
      isFav: true,
      isBrand: false,
      isSale: true,
    },
    {
      id: '2',
      name: 'Optimum Nutrition Gold Standard 100% Whey Protein Powder',
      color: '#f5a442',
      image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcR7cl4qCLRthQoxDc0tYnP5152GRJjEJuDGzTYAGWbVYvEfscF2Ojx680HtTMXpsfO-rg-cQer8rolddOUcwa09fd6r6XdrK9gm5mZtbDj8r6qhLi2fAtr5&usqp=CAc',
      categoryId: '1',
      description: 'Sự lựa chọn hàng đầu của nhiều vận động viên.',
      isFav: false,
      isBrand: true,
      isSale: false,
    },
    {
      id: '3',
      name: 'MuscleTech NitroTech Whey Protein Powder',
      color: '#f5d142',
      image: 'https://bizweb.dktcdn.net/thumb/grande/100/011/344/products/nitro-tech1.jpg?v=1647664795127',
      categoryId: '1',
      description: 'Một loại whey chất lượng cao giúp bạn tăng cơ nhanh chóng.',
      isFav: true,
      isBrand: true,
      isSale: true,
    },
    {
      id: '4',
      name: 'Dymatize ISO 100 Whey Protein Powder',
      color: '#368dff',
      image: 'https://bizweb.dktcdn.net/thumb/grande/100/011/344/products/dymatize-iso-100-5lbs-gourmet-chocolate-whey-protein-phat-trien-co-bap-gymstore.jpg?v=1638591261403',
      categoryId: '1',
      description: 'Whey protein đậm đặc có chất lượng cao và hương vị thơm ngon.',
      isFav: false,
      isBrand: true,
      isSale: false,
    },
    {
      id: '5',
      name: 'BSN Syntha-6 Whey Protein Powder',
      color: '#41d95d',
      image: 'https://wheyshop.cdn.vccloud.vn/wp-content/uploads/2020/04/Syntha-6-10lbs-454kg-1.jpg',
      categoryId: '1',
      description: 'Sự pha trộn hoàn hảo của các loại protein giúp tăng cơ và hồi phục nhanh chóng.',
      isFav: true,
      isBrand: true,
      isSale: false,
    },
    {
      id: '6',
      name: 'Cellucor C4 Pre-Workout Supplement',
      color: '#f54242',
      image: 'https://bizweb.dktcdn.net/thumb/1024x1024/100/011/344/products/c4-original-30-serving-orange-burst.jpg?v=1663575742217',
      categoryId: '2',
      description: 'Creatine giúp tăng sức mạnh và sức bền trong tập luyện.',
      isFav: false,
      isBrand: true,
      isSale: true,
      },

  {
  id: '7',
  name: 'Optimum Nutrition Micronized Creatine Powder',
  color: '#9eecff',
  image: 'https://product.hstatic.net/1000185761/product/optimum-nutritiion-creatine-powder-600g_grande.jpg',
  categoryId: '2',
  description: 'Creatine giúp tăng sức mạnh và sức bền trong tập luyện.',
  isFav: false,
  isBrand: true,
  isSale: true,
  },
  {
  id: '8',
  name: 'MusclePharm Combat Protein Powder',
  color: '#b9ffb0',
  image: 'https://vuagym.com/wp-content/uploads/2020/08/combat-powder-2-lbs-chocolate-wtm.jpg',
  categoryId: '1',
  description: 'Một loại protein đa dạng giúp tăng cơ và phục hồi cơ bắp.',
  isFav: true,
  isBrand: true,
  isSale: true,
  },
  {
  id: '9',
  name: 'Optimum Nutrition Essential Amino Energy',
  color: '#ffc7ff',
  image: 'https://vuagym.com/wp-content/uploads/2020/06/optimum-nutrition-amino-energy-30-lan-dung-wtm.jpg',
  categoryId: '2',
  description: 'Sản phẩm tăng cường năng lượng và sức bền trong tập luyện.',
  isFav: false,
  isBrand: true,
  isSale: false,
  },
  {
  id: '31',
  name: 'BSN AminoX BCAA Powder',
  color: '#3d3d3d',
  image: 'https://content.gobsn.com/i/bodyandfit/bsn-amino-x_Image_01?$TTL_PRODUCT_IMAGES$&locale=en-us,en-gb,*&layer0=$PDP_004$&fmt=webp',
  categoryId: '2',
  description: 'Sản phẩm BCAA cao cấp giúp phục hồi cơ bắp sau tập luyện.',
  isFav: true,
  isBrand: true,
  isSale: false,
  },
  {
    id: '41',
    name: 'Z Nutrition - OmegaWell (60 viên)',
    color: '#3d3d3d',
    image: 'https://vuagym.com/wp-content/uploads/2020/11/nutrition-omegawell-wtm.jpg',
    categoryId: '2',
    description: 'Omega là một trong những chất cần thiết nhất. Vì nó mang lại rất nhiều lợi ích cho sức khỏe.',
    isFav: true,
    isBrand: true,
    isSale: false,
    },
    {
      id: '19',
      name: 'Kevin Levrone - Vitamin C 1000 mg (90 viên)',
      color: '#3d3d3d',
      image: 'https://vuagym.com/wp-content/uploads/2022/08/vitamin-c-90v.jpg',
      categoryId: '2',
      description: 'Vitamin C góp phần duy trì sự tổng hợp bình thường của collagen, hỗ trợ tình trạng và chức năng thích hợp của xương, răng, màng nhầy và da',
      isFav: true,
      isBrand: true,
      isSale: false,
      },
      {
        id: '26',
        name: 'Elite Labs - Extreme Massive Mass Gainer (6 Lbs)',
        color: '#4a148c',
        image: 'https://vuagym.com/wp-content/uploads/2022/06/extreme-massive-mass-gainer-6lbs-choco.jpg',
        categoryId: '3',
        description: 'Với Extreme Massive Mass Gainer ™, bạn sẽ nhận được hơn 249 gram carb hoàn hảo cho những người khó tăng cân. Maltodextrin là một loại carbohydrate phức hợp làm tăng insulin cao, thúc đẩy các aminos tăng khối lượng vào cơ bắp của bạn và giúp thúc đẩy trạng thái đồng hóa cao. Sau đó, nó đốt cháy từ từ để giúp hạn chế tăng mỡ và giảm lượng đường trong máu. Đây là loại carb tối ưu dành cho người khó tăng cân và mang lại cho bạn sức mạnh để thoát khỏi cơ thể nhỏ bé.',
        isFav: true,
        isBrand: true,
        isSale: true,
      },
      {
        id: '21',
        name: 'REPP Sports - Raze Mass Gainer (12 Lbs)',
        color: '#4a148c',
        image: 'https://vuagym.com/wp-content/uploads/2023/04/raze-mass-gainer-12lbs.jpg',
        categoryId: '3',
        description: 'Sản phẩm này còn được thiết kế đặc biệt để tăng cường quá trình phục hồi cơ bắp sau khi tập luyện, giúp bạn tăng cường khả năng chịu đựng và tập luyện hiệu quả hơn.',
        isFav: true,
        isBrand: true,
        isSale: true,
      },
      {
        id: '18',
        name: 'Universal Nutrition Animal Pak Multivitamin',
        color: '#9eecff',
        image: 'https://cdn.shopify.com/s/files/1/0675/6882/8736/products/AnimalPak44.png?v=1676457544&width=1200',
        categoryId: '4',
        description: 'Thực phẩm bổ sung đa vitamin và khoáng chất dành cho tập gym.',
        isFav: false,
        isBrand: true,
        isSale: false,
        },
        {
          id: '27',
          name: 'VitaXtrong - Mega Mass Pro 1350 (6 Lbs)',
          color: '#4a148c',
          image: 'https://vuagym.com/wp-content/uploads/2021/02/mega-mass-pro-1350-6lbs-wtm.jpg',
          categoryId: '3',
          description: 'Mega Mass Pro là một sản phẩm kết hợp dinh dưỡng hoàn chỉnh: Tinh bột (Carb), Đạm (Protein) và các Khoáng Chất, Vitamin thiết yếu',
          isFav: true,
          isBrand: true,
          isSale: true,
        },
    {
        id: '21',
        name: 'OstroVit - KSM-66 Ashwagandha (120 viên)',
        color: '#8f9dff',
        image: 'https://vuagym.com/wp-content/uploads/2023/04/ostrovit-ksm-66-ashwagandha-120-vien.jpg',
        categoryId: '4',
        description: 'Là một sản phẩm bổ sung dinh dưỡng được làm từ cây Ashwagandha (Withania somnifera) và chứa chiết xuất KSM-66. Ashwagandha là một loại thực vật được sử dụng trong y học cổ truyền Ấn Độ và Trung Quốc, KSM-66 là một loại chiết xuất độc quyền của Ashwagandha, được sản xuất bằng phương pháp truyền thống và được cho là có hiệu quả cao hơn so với các loại chiết xuất khác.',
        isFav: true,
        isBrand: false,
        isSale: true,
    },
    {
        id: '32',
        name: 'Ostrovit - Liposomal Magnesium (240 viên)',
        color: '#4a4a4a',
        image: 'https://vuagym.com/wp-content/uploads/2023/04/ostrovit-liposomal-magnesium-240-vien.jpg',
        categoryId: '4',
        description: 'Magie là một khoáng chất cần thiết, giúp hỗ trợ nhiều chức năng trong cơ thể, Liposomal Magnesium là một loại Magnesium mới được sản xuất dưới dạng vi khuẩn nhân tạo và bao phủ bởi các lớp Phosholipid, giúp cho việc hấp thu Magnesium tốt hơn. Đây là dạng bổ sung Magnesium được cho là có hiệu quả tốt hơn so với các dạng Magnesium thông thường.',
        isFav: false,
        isBrand: false,
        isSale: false,
    },
    {
        id: '51',
        name: 'Applied Nutrition - Omega 3 (100 viên)',
        color: '#4a4a4a',
        image: 'https://vuagym.com/wp-content/uploads/2021/04/applied-nutrition-omega-3-100v-wtm.jpg',
        categoryId: '4',
        description: 'Omega 3 là một Axit béo thiết yếu có nguồn gốc từ Dầu cá, rất giàu EPA (Axit Eicosapentaenoic) và DHA (Axit Docosahexaenoic). Vì con người không có khả năng tổng hợp Omega 3, nên điều cần thiết là chúng ta phải tiêu thụ chúng qua các nguồn thực phẩm.',
        isFav: false,
        isBrand: false,
        isSale: false,
    },
    {
        id: '47',
        name: 'OstroVit - Electrolytes (20 viên)',
        color: '#4a4a4a',
        image: 'https://vuagym.com/wp-content/uploads/2023/04/ostrovit-electrolytes-20-vien.jpg',
        categoryId: '4',
        description: 'Điện giải là một quá trình quan trọng trong cơ thể của con người, giúp duy trì cân bằng nước và các chất điện giải quan trọng. Tuy nhiên, trong một số trường hợp, cơ thể của chúng ta có thể bị mất cân bằng về điện giải, đặc biệt là khi chúng ta vận động hoặc tập luyện nặng. Để giải quyết vấn đề này, sản phẩm OstroVit – Electrolytes được phát triển để cung cấp điện giải cho cơ thể của bạn.',
        isFav: false,
        isBrand: false,
        isSale: false,
    },
    {
        id: '48',
        name: 'BioTechUSA - Multi Hypotonic',
        color: '#4a4a4a',
        image: 'https://vuagym.com/wp-content/uploads/2022/03/bio-multi-hypotonic-1000ml-forest-wtm.jpg',
        categoryId: '4',
        description: 'Multi Hypotonic BiotechUSA là một loại thức uống thể thao dạng lỏng cô đặc, được tinh chế riêng với carbohydrate đáp ứng lượng đường hydrate cao và nhiều loại vitamin, giúp bổ sung năng lượng và vitamin bị mất trong quá trình tập luyện.',
        isFav: false,
        isBrand: false,
        isSale: false,
    },
    {
      id: '11',
      name: 'MuscleTech - Mass Tech Extreme 2000 (12 Lbs)',
      color: '#4a148c',
      image: 'https://vuagym.com/wp-content/uploads/2023/01/mass-tech-extreme-12-lbs-choco.jpg',
      categoryId: '3',
      description: 'Cho dù bạn đang bị chững cân trong thời gian dài hoặc chỉ có một thời gian khó khăn về việc tăng cơ nạc, bây giờ bạn đã có công cụ giúp bạn thoát khỏi những rào càn này. Nó được gọi là MASS-TECH EXTREME 2000!',
      isFav: true,
      isBrand: true,
      isSale: true,
    },
    {
      id: '16',
      name: 'Myprotein - Clear Whey Gainer (1.95 Kg)',
      color: '#4a148c',
      image: 'https://vuagym.com/wp-content/uploads/2022/06/clear-whey-gainer-195kg-rasperry-wtm.jpg',
      categoryId: '3',
      description: 'Clear Whey Gainer không phải loại sữa tăng cân bình thường.  Chúng tôi đã sử dụng protein thủy phân cô lập chất lượng cao và làm ra một sữa tăng cân sảng khoái — Đó giống như nước trái cây hơn là sữa lắc protein.',
      isFav: true,
      isBrand: true,
      isSale: true,
    },
    {
      id: '30',
      name: 'OstroVit - GAINlicious Mass Gainer (4.5KG)',
      color: '#4a148c',
      image: 'https://vuagym.com/wp-content/uploads/2022/05/gainlicious-mass-gainer-white-choco-wtm.jpg',
      categoryId: '3',
      description: 'Bổ sung hàm lượng calo cao chứa carbohydrate, protein và chất béo, bao gồm cả axit béo bão hòa. Sản phẩm có thể giúp bạn xây dựng khối lượng cơ bắp, cung cấp cho bạn các thành phần hỗ trợ tăng cân. Nhờ có dạng bột tiện dụng, gainer rất dễ chuẩn bị và có thể mang đi mọi nơi – đến phòng tập, đến nơi làm việc, đến trường đại học hoặc trong một chuyến du lịch. Là 1 bữa ăn thay thế cân bằng có thể giúp bạn nhanh chóng đáp ứng nhu cầu năng lượng hàng ngày của cơ thể.',
      isFav: true,
      isBrand: true,
      isSale: true,
    },
];

export default PRODUCTS;